### PR TITLE
Changes to magazine handling

### PR DESCRIPTION
**Pull request by philborman**
Date checking improved
Magazine month names now checked in English and also in users default locale
Magazines with unrecognised dates added to "Past Issues" table with other skipped issues
Issues in "Past Issues" list can now be selected manually and downloaded
Tidied parameter passing to database calls

### CODE REVIEW

**Comment by nigelhooper** [comment]
@philborman the changes you have just merged to formatter.py are missing the trailing colons for the elif statements which is causing an error.  i.e. this line and similar following ones:

elif month == datetime.date(2015, 1, 1).strftime("%B")
return "01"

**Comment by maxcore** [comment]
@philborman cant start the package now

````
File "/Users/maxcore/Downloads/LazyLibrarian-master 2/LazyLibrarian.py", line 4, in <module>
    import lazylibrarian
  File "/Users/maxcore/Downloads/LazyLibrarian-master 2/lazylibrarian/__init__.py", line 12, in <module>
    from lazylibrarian import logger, postprocess, searchnzb, searchtorrents, SimpleCache, librarysync
  File "/Users/maxcore/Downloads/LazyLibrarian-master 2/lazylibrarian/logger.py", line 6, in <module>
    from lazylibrarian import formatter
  File "/Users/maxcore/Downloads/LazyLibrarian-master 2/lazylibrarian/formatter.py", line 68
    elif month == datetime.date(2015, 1, 1).
````

**Comment by philborman** [comment]
Sorry, silly mistake in cut-and-paste. Have uploaded a fix but waiting 
for nncrypted to pull it into master.
That will teach me not to develop on one machine and upload from another ;-)

**Comment by nigelhooper** [comment]
I can confirm that the errors are fixed.

**Comment by maxcore** [comment]
i confirm too thx @philborman !!!

**Pull request merged**
