### PR TITLE
Add Prowl notifier support

### PR DESCRIPTION
**Pull request by barbequesauce**
Third time's a charm. Adding Prowl notifier support. Based heavily on NMA.

### CODE REVIEW

**Comment by barbequesauce** [comment]
I think i have my Git desktop issues worked out finally. It could still use some testing...

**Comment by philborman** [comment]
ok, got it working here (with no account, just checking communication)
At the top of the file you are missing a couple of imports
from httplib import HTTPSConnection
from urllib import urlencode

and at the end of the file three logger.info messages refer to module which is undefined. Just replace with "Prowl:"

Hope this helps...

**Comment by barbequesauce** [comment]
OK, cleaned up the unknown module calls.
Were there other missing imports? I had both of those in my uploaded copy already..

**Comment by philborman** [comment]
Many thanks, seems to work fine now. I get "Unauthorised" as a response, invalid api key.

**Comment by maxcore** [comment]
SyntaxError: invalid syntax
Traceback (most recent call last):
File "/app/lazylibrarian/LazyLibrarian.py", line 13, in <module>
import lazylibrarian
File "/app/lazylibrarian/lazylibrarian/__init__.py", line 30, in <module>
from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
File "/app/lazylibrarian/lazylibrarian/postprocess.py", line 35, in <module>
from lazylibrarian.notifiers import notify_download, custom_notify_download
File "/app/lazylibrarian/lazylibrarian/notifiers/__init__.py", line 22, in <module>
import prowl
File "/app/lazylibrarian/lazylibrarian/notifiers/prowl.py", line 51
response = http_handler.getresponse()

???

**Comment by barbequesauce** [comment]
Looks like @philborman beat me to it - see #853

**Pull request merged**
