### PR TITLE
Magazine db reduction

### PR DESCRIPTION
**Pull request by Code-Slave**
This combines queries when entering magazine section. Instead of looping through each magazine and querying issues I added it to top query.

### CODE REVIEW

**Comment by philborman** [comment]
I think this can be shortened more...
Instead of 
                count = mag['issue_cnt']
                 if count:
                    issues = mag['issue_cnt']
                 else:
                     issues = 0

can you just do
                    issues = mag['issue_cnt']
I think the "count" variable  is superfluous

**Comment by Code-Slave** [comment]
Yep. query returns 0 so the assignment works

**Comment by Code-Slave** [comment]
this took my magazine queries from over 700 to ~40

**Comment by philborman** [comment]
Wow, 700 down to 40, that's some optimisation.
Seems to have a problem with an empty magazine table though. Returns a line of results with all fields null except the count which is zero. LazyLibrarian then baulks at a null value for title. I tried adding 
where  m.Title is not NULL and m.Title is not ''   but that seemed to have no effect. 

sqlite> select m.*, count(i.title) as issue_cnt from magazines m , issues i where m.Title is not NULL and m.Title is not '' and m.Title = i.Title ORDER by Title;
|||||||||0

**Comment by Code-Slave** [comment]
Ill have a look this evening. I disnt take ito account an empty table. Ill rework the logic

**Comment by Code-Slave** [comment]
i added a query before loop to make it functional. still reduced the calls but its kind of ugly. handles empty table now

**Comment by philborman** [comment]
Works great now, thanks for that!

**Comment by philborman** [comment]
Just added some more indexes for "Status" searches on author/book/wanted tables. Seems to help. I used "explain query plan" to make sure indexes were being used - is that the best way?  

All my updates are complete for now, so shouldn't be any more merge/commit issues :-)

**Pull request merged**
