### PR TITLE
Changes to external "convert" program, configured value overrides pythonmagick/wand

### PR DESCRIPTION
**Pull request by philborman**

### CODE REVIEW

**Comment by philborman** [comment]
Wow that was fast!

I think issues 193  195  196  198  202  204  208  210   can all be closed now

**Comment by nncrypted** [comment]
done :) and thank you for the amazing work you've put into this project.

**Comment by philborman** [comment]
You're welcome,
LL does just about everything I want it to now, so things should quieten 
down a bit.
We could do with the web interface being tidied up, especially for small 
screens like mobiles,
but that's way out of my comfort zone.

Learning a bit of python was fun though.

oh, and
Happy New Year!

**Comment by nncrypted** [comment]
Happy New Year to you also.

**Comment by maxcore** [comment]
good point for mobile skin ;)

**Pull request merged**
