### PR TITLE
new indexes

### PR DESCRIPTION
**Pull request by Code-Slave**
created a couple helper indexes for queries.

### CODE REVIEW

**Comment by Code-Slave** [comment]
db upgraded to 25

**Comment by philborman** [comment]
Thanks for this, does anything use the new indexes yet, or is it a sqlite optimisation? Database stuff isn't really my field!

I was just about to push a v25 database upgrade, I will rename mine to v26. New sync table for syncing user read/toread with calibre custom columns.

**Comment by philborman** [comment]
I just noticed the indexes are not created for a new database, only upgrades, so added the two CREATE INDEX lines at line 169 as well.

**Comment by Code-Slave** [comment]
oops missed that. im still getting familiar with the code. Yes the indexes are used in current queries. I am a huge DB nerd so thats why im looking there

**Pull request merged**
