### PR TITLE
Pull the book from Goodread to get the original pubdate

### PR DESCRIPTION
**Pull request by knobunc**
The list api doesn't show the original publication date, just the last edition of the work.  Pull the work so that we can get the original pubdate.  For collections it seems to return the original pubdate of the collection, or the first book date.  Either is fine.

### CODE REVIEW

**Comment by philborman** [comment]
Holding off on this one, there are quite strict api limits on goodreads, 1 call per second, max 1000 per 24hrs and calling once for each book will soon get you blocked.

The "series info" call gives you original publication date and one call gets the info for all books in the series which is much less of a problem. I think the code for that was added just before I went away, if not then it's sitting in my git waiting to be pushed.

Books that are not in a series still might not have the original publication date, goodreads gives us the "best book" date, whatever that means.

Maybe we could drip feed the dates on the Non-series books, either a separate task or when we refresh each author to keep the number of api calls down, what do you think?

**Comment by knobunc** [comment]
Yeah, no worries.  I'll see if I can pull the date from the series first.

**Comment by philborman** [comment]
Just pushed the code that grabs original pub date for books in a series (and caches it for other series members), need to figure out the best way to do it for non-series members. We can fairly easily check if the book is part of a series, but when should we actually do the extra api call?  Also if we don't know the language or isbn for a book we get the book page which includes the original_pub_date so we couls update then but doesn't happen often. Maybe we should add another field to the books table to keep track of whether we've already searched for the book page, or maybe we check the cache without downloading?

**Comment by philborman** [comment]
Tempted to add original_book_date as an extra column to the database. Use that date if present, if not use the goodreads last edition date, what do you think?
actually I don't think it's "latest edition" that goodreads gives us, they call it "best book" whatever that means :-)

**Comment by philborman** [comment]
I have added original publication date to book table and moved your new get_book_pubdate function into bookwork.py. The code in gr.py has been reordered to get series info and language code first, as these pull in pages that include the original publication date, and we don't ask for the date if a book is going to be ignored for any reason. Cuts down the api calls dramatically. See how it goes, if we get blocked it might have to be tweaked a bit more. Thanks for the code!

**Comment by knobunc** [comment]
Awesome!  Thank you!

**Pull request closed without merging**
