### PR TITLE
A few minor bug fixes

### PR DESCRIPTION
**Pull request by philborman**
Only report stats on rescan if new books found
Ensure book names don't contain quotes
Tidied up magazine status changes and log messages
Bug fix trying to open missing books
Better error reporting for missing books
Removed bool as config option, use int instead

### CODE REVIEW

**Comment by maxcore** [comment]
nice job @philborman ! 
you know What is Jackett ?
https://github.com/Jackett/Jackett :)

**Comment by philborman** [comment]
I had a quick look, seems interesting, but the downloads page 
http://jackett.net/Download does not work
On the github page the downloads don't contain JackettConsole.exe so I 
can't try it.

**Comment by maxcore** [comment]
@philborman 

https://www.dropbox.com/s/9j70sgf5nfg0rv9/Jackett.Mono.v0.6.8.tar.bz2?dl=0

the mine .

the git and homepage has a new owner the link will be back soon on the homepage

**Comment by philborman** [comment]
Thanks for the link.
I had a look at jackett, but I don't think it is much use for 
lazylibrarian at the moment.
Most of the torrent site links are invite only, and the few open ones 
only do movies and tv shows.
On the webpage they say they are working on extending the program to 
cover music and comics.
If ebooks are added it may be more use in the future.

Kind regards

**Pull request merged**
